# ========================================
# Portainer Stack Configuration for CoffeeBot
# ========================================
# 
# تعليمات:
# 1. انسخ هذا المحتوى كاملاً
# 2. في Portainer: Stacks > Add Stack
# 3. اختر اسم (مثل: coffeebot)
# 4. الصق هذا الملف في Web editor
# 5. أسفل الشاشة، أضف Environment Variables (انظر تحت)
# 6. اضغط Deploy Stack
#
# ========================================

version: '3.8'

services:
  bot:
    # استخدم صورة موجودة أو build من Dockerfile
    # Option 1: من Docker Hub
    image: abdulaziz/coffeebot:latest
    
    # Option 2: build محلي (إذا عملت upload للملفات)
    # build:
    #   context: ./bot
    #   dockerfile: Dockerfile
    
    container_name: coffeebot_telegram
    restart: unless-stopped
    
    # قراءة المتغيرات من Portainer Environment
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - ADMIN_IDS=${ADMIN_IDS}
      - ADMIN_GROUP_ID=${ADMIN_GROUP_ID}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TZ=Asia/Riyadh
    
    # تخزين السجلات خارج الكونتينر
    volumes:
      - ./logs:/app/logs:rw
    
    # إعدادات التسجيل
    logging:
      driver: "json-file"
      options:
        max-size: "10m"      # حجم الـ log الواحد
        max-file: "3"        # عدد الملفات المحفوظة
    
    # تشبيك (للتوسع في المستقبل)
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

# ========================================
# Environment Variables المطلوبة
# ========================================
#
# BOT_TOKEN
# القيمة: توكن البوت من @BotFather
# مثال: 432166173:AAEVpOpUPyQ4lrpnrFyuu1scGZSSGQ17xTs
#
# MONGO_URI
# القيمة: رابط MongoDB Atlas
# مثال: mongodb+srv://usar:password@coffeebot.0zmxd.mongodb.net/?appName=coffeeBot
#
# MONGO_DB_NAME
# القيمة: اسم قاعدة البيانات في MongoDB
# مثال: coffeeBot
#
# ADMIN_IDS
# القيمة: معرفات الأدمن (واحد أو أكثر مفصول بفاصلة)
# مثال: 218369077
# أو: 218369077,123456789,987654321
#
# ADMIN_GROUP_ID
# القيمة: معرف مجموعة الأدمن (يجب أن يكون سالب)
# مثال: -1001234567890
#
# LOG_LEVEL (اختياري)
# القيمة: INFO, DEBUG, WARNING, ERROR
# الافتراضي: INFO
#
# ========================================
